DROP TABLE IF EXISTS STAVKA_LOYALTY;
DROP TABLE IF EXISTS KNJIGA_AUTOR;
DROP TABLE IF EXISTS STAVKAPOZAJMICE;
DROP TABLE IF EXISTS POZAJMICA;
DROP TABLE IF EXISTS KNJIGA;
DROP TABLE IF EXISTS AUTOR;
DROP TABLE IF EXISTS LOYALTYPRAVILO;
DROP TABLE IF EXISTS STATUSPOZAJMICE;
DROP TABLE IF EXISTS CLAN;
DROP TABLE IF EXISTS ULOGA;

CREATE TABLE ULOGA(
  id_uloga INT AUTO_INCREMENT PRIMARY KEY,
  naziv VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE CLAN (
  id_clan INT AUTO_INCREMENT PRIMARY KEY,
  ime VARCHAR(100) NOT NULL,
  prezime VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  telefon VARCHAR(50),
  adresa VARCHAR(255),
  datum_uclanjenja DATE NOT NULL,
  ukupno_poena INT NOT NULL DEFAULT 0,
  id_uloga INT NOT NULL,
  CONSTRAINT fk_clan_uloga
  FOREIGN KEY (id_uloga) REFERENCES ULOGA(id_uloga)
  ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE STATUSPOZAJMICE (
  id_status INT AUTO_INCREMENT PRIMARY KEY,
  naziv VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE LOYALTYPRAVILO (
  id_pravilo INT AUTO_INCREMENT PRIMARY KEY,
  naziv VARCHAR(100) NOT NULL,
  opis VARCHAR(255),
  tip_obracuna VARCHAR(50) NOT NULL,
  vrednost_poena INT NOT NULL
);

CREATE TABLE AUTOR (
  id_autor INT AUTO_INCREMENT PRIMARY KEY,
  ime VARCHAR(100) NOT NULL,
  prezime VARCHAR(100) NOT NULL
);

CREATE TABLE KNJIGA (
  id_knjiga INT AUTO_INCREMENT PRIMARY KEY,
  naslov VARCHAR(255) NOT NULL,
  isbn VARCHAR(32) NOT NULL UNIQUE,
  godina_izdanja INT,
  izdavac VARCHAR(150),
  opis VARCHAR(250),
  dostupna BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE POZAJMICA (
  id_pozajmica INT AUTO_INCREMENT PRIMARY KEY,
  id_clan INT NOT NULL,
  datum_pozajmice DATE NOT NULL,
  datum_roka_pozajmice DATE NOT NULL,
  ukupna_kazna DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  ukupan_broj_poena INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_pozajmica_clan FOREIGN KEY (id_clan) REFERENCES CLAN(id_clan) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE STAVKAPOZAJMICE (
  id_stavka INT AUTO_INCREMENT PRIMARY KEY,
  id_pozajmica INT NOT NULL,
  id_knjiga INT NOT NULL,
  id_status INT NOT NULL,
  broj_poena INT NOT NULL DEFAULT 0,
  kazna DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  datum_vracanja DATE NULL,
  CONSTRAINT fk_stavka_pozajmica FOREIGN KEY (id_pozajmica) REFERENCES POZAJMICA(id_pozajmica) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_stavka_knjiga FOREIGN KEY (id_knjiga) REFERENCES KNJIGA(id_knjiga) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_stavka_status FOREIGN KEY (id_status) REFERENCES STATUSPOZAJMICE(id_status) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE KNJIGA_AUTOR (
  id_knjiga INT NOT NULL,
  id_autor INT NOT NULL,
  PRIMARY KEY (id_knjiga, id_autor),
  CONSTRAINT fk_ka_knjiga FOREIGN KEY (id_knjiga) REFERENCES KNJIGA(id_knjiga) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ka_autor  FOREIGN KEY (id_autor)  REFERENCES AUTOR(id_autor) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE STAVKA_LOYALTY (
  id_aplikacije BIGINT AUTO_INCREMENT PRIMARY KEY,
  id_stavka INT NOT NULL,
  id_pravilo INT NOT NULL,
  poeni INT NOT NULL,
  napomena VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_stavka_pravilo UNIQUE (id_stavka, id_pravilo),
  CONSTRAINT fk_sl_stavka FOREIGN KEY (id_stavka) REFERENCES STAVKAPOZAJMICE(id_stavka) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_sl_pravilo FOREIGN KEY (id_pravilo) REFERENCES LOYALTYPRAVILO(id_pravilo) ON DELETE CASCADE ON UPDATE CASCADE
);
